name: novelnooks
description: "A new Flutter eBook app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  auto_route: ^7.8.4
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.3
  dio: ^5.4.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  flutter:
    sdk: flutter
  flutter_icons:
    git: https://github.com/jibiel/flutter-icons
  flutter_web_plugins:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_spinkit: ^5.2.0
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.4
  path: ^1.8.2
  path_provider: ^2.1.0
  permission_handler: ^11.1.0
  riverpod_annotation: ^2.1.1
  share_plus: ^7.2.1
  shared_preferences: ^2.1.1
  uuid: ^4.2.2
  device_info_plus: ^10.1.2
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  material_design_icons_flutter: ^7.0.7296
  lottie: ^2.7.0
  pin_code_fields: ^8.0.1
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^18.0.1
  firebase_in_app_messaging: ^0.7.5+7
  equatable: ^2.0.7
  timeago: ^3.7.0
  shimmer: ^3.0.0
  emoji_picker_flutter: ^4.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  carousel_slider: ^5.0.0
  flutter_epub_viewer: ^1.2.1
  confetti: ^0.8.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  firebase_dynamic_links: ^5.5.7

dependency_overrides:
  collection: ^1.17.2
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.3.4
  riverpod_generator: ^2.2.3
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/app-logo.png
    - assets/icons/google-icon.png

